import { ENV_GROUP_NOTES, ENV_GROUPS, ENV_VARS, type EnvGroup } from '../../src/core/envCatalog'

export const GENERATED_NOTE = '<!-- Generated by `npm run docs:gen` (scripts/gen-docs.ts). Do not edit by hand. -->'

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ')
const groups = () => Object.keys(ENV_GROUPS) as EnvGroup[]

export function renderConfigurationMd(): string {
  const out = [
    GENERATED_NOTE,
    '',
    '# Configuration',
    '',
    'Every environment variable the bridge reads. Copy `.env.example` to `.env` (Node, Docker Compose) or set these in your host (Railway → service → Variables).',
    'Empty values count as unset. Environment variables always win over `/setup`; `/setup` shows them as "set by env".',
    'Everything else (formats, ranks, commands, join requirements, filters) is configured in Discord with `/setup`.',
    ''
  ]
  for (const group of groups()) {
    const rows = ENV_VARS.filter(v => v.group === group)
    if (rows.length === 0) continue
    out.push(`## ${ENV_GROUPS[group]}`, '')
    if (ENV_GROUP_NOTES[group]) out.push(ENV_GROUP_NOTES[group], '')
    out.push('| Variable | Required | Default | Description |', '|---|---|---|---|')
    for (const v of rows) {
      const name = `\`${v.name}\`${v.secret ? ' 🔒' : ''}`
      out.push(`| ${name} | ${v.required ? 'yes' : 'no'} | ${v.default ? `\`${cell(v.default)}\`` : '—'} | ${cell(v.description)} |`)
    }
    out.push('')
  }
  out.push('🔒 = secret. Never paste it into an issue, a log excerpt or a screenshot.', '')
  return out.join('\n')
}

export function renderEnvExample(): string {
  const out = ['# Generated by `npm run docs:gen` from src/core/envCatalog.ts. Full reference: docs/configuration.md', '# Empty values mean "unset" (the default is used).', '']
  for (const group of groups()) {
    if (group === 'platform') continue
    const rows = ENV_VARS.filter(v => v.group === group && v.readBy === 'bridge')
    if (rows.length === 0) continue
    const title = ENV_GROUPS[group]
    out.push(`# ── ${title} ${'─'.repeat(Math.max(3, 70 - title.length))}`)
    for (const v of rows) {
      const indexed = v.name.includes('<n>')
      const key = `${indexed ? '# ' : ''}${v.name.replace('<n>', '2')}=`
      out.push(`${key.padEnd(36)}# ${v.description}${v.default ? ` Default: ${v.default}.` : ''}`)
    }
    out.push('')
  }
  return out.join('\n')
}
